class Correction_Template():
	"""
	This class is a template for all correction helper classes
	"""

	def fix(self, data: dict) -> dict:
		# This will be implemented (default template) automatically in each autogenerated subclass
		pass
